"""Write the queue as a Python script that does the same measurements with plain QCoDeS (no Qt).

``generate_script(recipes, context, definitions)`` returns the text of a script that loads the station, builds the
experiment parameters the recipes use (the way the application does), and runs each recipe with ``dond(...)``: the same
sweeps, measured parameters, repetitions, actions, datasets and options. It needs QCoDeS and the station file (and the
drivers the station uses), not the application window. The few pieces of mesoscopy that the application relies on
(snake sweeps, traces) are copied into the script as they are.
"""
import ast
import inspect
import json
import re
from datetime import datetime

from mesoscopy.core import queue_steps, recipes as recipe_tools
from mesoscopy.core.dond_options import normalise_advanced
from mesoscopy.core.run_setup import required_definitions
from mesoscopy.core.experiment_parameters import RAMP_INTER_DELAY, expression_names

HEADER = '''#!/usr/bin/env python
"""Generated by mesoscopy on {date} from the run queue ({count} measurement(s)).

Runs the same measurements as the application, with plain QCoDeS: it loads the station file, builds the experiment
parameters the measurements use (named as in the Parameter explorer), and calls dond for each measurement, one after the
other.

Check the SETTINGS below (the station file and the database path are those of the computer it was exported on), then run:
    python {name}
The measurements start at once. Parameters are set with their safe limits and ramp rates, as in the application.
"""
import time
import traceback

import numpy as np
from scipy import constants as const
import qcodes
from qcodes import validators as vals
from qcodes.dataset import (
    ArraySweep, LinSweep, LogSweep, TogetherSweep, dond, initialise_or_create_database_at, load_or_create_experiment,
)
from qcodes.parameters import DelegateParameter, Parameter, ParameterWithSetpoints
from qcodes.station import Station
'''

HELPERS = '''

def find(path):
    """The parameter at ``path`` (names from the station root), e.g. ['dac', 'ch1']."""
    node = station.components[path[0]]
    for name in path[1:]:
        if hasattr(node, "submodules") and name in node.submodules:
            node = node.submodules[name]
        elif hasattr(node, "parameters") and name in node.parameters:
            node = node.parameters[name]
        else:  # a channel list is searched by the name of its channels
            node = next(ch for ch in node if ch.short_name == name)
    return node


def delegate(name, source, unit="", gain=1.0, low=None, high=None, rate=None):
    """An experiment parameter: ``source`` seen under ``name`` with a gain, safe limits and a maximum ramp rate."""
    if isinstance(source, ParameterWithSetpoints) and not hasattr(source, "source"):
        return source  # the trace of a driver is measured as it is
    kwargs = {"label": name, "unit": unit or source.unit}
    if gain != 1:
        kwargs["scale"] = 1 / gain
    numeric = source.vals is None or isinstance(source.vals, (vals.Numbers, vals.Ints))
    if source.settable and numeric:
        kwargs["vals"] = vals.Numbers(-np.inf if low is None else low, np.inf if high is None else high)
        if rate:
            kwargs["inter_delay"] = __INTER_DELAY__
            kwargs["step"] = rate * __INTER_DELAY__
    return DelegateParameter(name, source=source, **kwargs)


def derived(name, expression, dependencies, unit=""):
    """A get-only parameter computed from other experiment parameters."""
    code = compile(expression, "<expression>", "eval")

    def compute():
        values = {key: parameter.get() for key, parameter in dependencies.items()}
        return eval(code, {"np": np, "numpy": np, "const": const}, values)

    return Parameter(name, get_cmd=compute, set_cmd=False, label=name, unit=unit)


def make_action(name, code, namespace):
    """An action of the measurement: Python code run in ``namespace``, with an error that names the action."""
    compiled = compile(code, f"<action {name}>", "exec")

    def run():
        try:
            exec(compiled, namespace)
        except Exception as e:
            raise RuntimeError(f"Action '{name}' failed: {type(e).__name__}: {e}") from e

    return run


def measured_parameter(alias, parameter):
    """(name in the dataset, parameter): measured under ``alias``, a trace under its own name."""
    alias = alias or parameter.full_name
    if alias == parameter.full_name or isinstance(parameter, ParameterWithSetpoints):
        return parameter.full_name if alias == parameter.full_name else alias, parameter
    return alias, DelegateParameter(alias, source=parameter)


class Breakout:
    """dond's break_condition for the breakout conditions of the experiment parameters. ``items``: [(name, parameter,
    operator, threshold, absolute)]. mode "any": stop when one is true; "all": when all are true at once."""

    OPERATORS = {">": np.greater, ">=": np.greater_equal, "<": np.less, "<=": np.less_equal}

    def __init__(self, items, measured, mode="any"):
        self.items, self.mode, self.reason = items, mode, None
        self._measured = {id(p) for p in measured}

    def __call__(self):
        hits = []
        for name, parameter, operator, threshold, absolute in self.items:
            try:
                value = float(parameter.get_latest() if id(parameter) in self._measured else parameter.get())
            except Exception as e:  # a reading that fails stops the run: better than running blind
                self.reason = f"breakout: could not read {name} ({type(e).__name__}: {e})"
                return True
            if self.OPERATORS[operator](abs(value) if absolute else value, threshold):
                hits.append((name, value))
        if self.items and (len(hits) == len(self.items) if self.mode == "all" else bool(hits)):
            self.reason = "breakout: " + ", ".join(f"{n} = {v:.4g}" for n, v in hits)
            return True
        return False
'''


def _literal(value):
    return repr(value)


def _text(code):
    """Python source for a string of code: triple-quoted when that reads well, else its repr."""
    if '"""' not in code and "\\" not in code and not code.endswith('"'):
        return '"""' + code + '"""'
    return repr(code)


def _path_literal(path):
    return repr(list(path or []))


def _float(text, default=0.0):
    try:
        return float(text)
    except (TypeError, ValueError):
        return default


def _definition_code(definition, names):
    """The lines that build one experiment parameter (a dict from ``ParameterDefinition.to_dict``)."""
    name = definition["name"]
    kind = definition.get("kind", "instrument")
    if kind == "root":
        return [f'{name} = station.components["{name}"]']
    if kind == "derived":
        dependencies = sorted(expression_names(definition.get("expression", "")))
        deps = "{" + ", ".join(f'"{n}": {n}' for n in dependencies if n in names) + "}"
        return [f'{name} = derived("{name}", {_literal(definition.get("expression", ""))}, {deps}, unit={_literal(definition.get("unit", ""))})']
    if kind == "trace":
        axis_source = (f"find({_path_literal(definition.get('axis_source'))})"
                       if definition.get("axis_kind") == "parameter" else "None")
        axis_name = definition.get("axis_name") or f"{name}_axis"
        return [
            f"_axis_{name} = AxisParameter({_literal(axis_name)}, {_literal(definition.get('axis_name') or '')}, "
            f"{_literal(definition.get('axis_unit', ''))}, {_literal(definition.get('axis_start', 0.0))}, "
            f"{_literal(definition.get('axis_stop', 1.0))}, {_literal(definition.get('axis_points', 101))}, {axis_source})",
            f"{name} = TraceParameter({_literal(name)}, find({_path_literal(definition.get('source'))}), _axis_{name}, "
            f"label={_literal(name)}, unit={_literal(definition.get('unit', ''))})",
        ]
    kwargs = [f"unit={_literal(definition.get('unit', ''))}"]
    if definition.get("gain", 1.0) != 1:
        kwargs.append(f"gain={_literal(definition['gain'])}")
    for key, arg in (("min_value", "low"), ("max_value", "high"), ("max_ramp_rate", "rate")):
        if definition.get(key) is not None:
            kwargs.append(f"{arg}={_literal(definition[key])}")
    return [f'{name} = delegate("{name}", find({_path_literal(definition.get("source"))}), {", ".join(kwargs)})']


def _axis_lines(dimension, variables, index):
    """The lines that build one axis of a recipe: ``sweep_<index> = ...``."""
    kind = dimension.get("class", "LinSweep")
    delay = _float(dimension.get("delay"), 0.0)
    get_after_set = bool(dimension.get("get_after_set"))
    actions = [a for a in dimension.get("actions") or [] if a.get("enabled", True)]
    post = ("[" + ", ".join(f"make_action({_literal(a['name'])}, {_text(a['code'])}, namespace)" for a in actions) + "]"
            if actions else "[]")
    extra = f", post_actions={post}" if actions else ""
    extra += ", get_after_set=True" if get_after_set else ""
    lines = []
    if kind == "TogetherSweep":
        pieces = []
        for n, path in enumerate(dimension.get("together") or []):
            start = _float((dimension.get("together_starts") or [])[n], 0.0)
            stop = _float((dimension.get("together_stops") or [])[n], 1.0)
            pieces.append(f"LinSweep({path[0]}, {start!r}, {stop!r}, {int(dimension.get('num', 101))}, {delay!r}"
                          + (extra if n == 0 else (", get_after_set=True" if get_after_set else "")) + ")")
        return [f"sweep_{index} = TogetherSweep(", *[f"    {p}," for p in pieces], ")"]
    parameter = (dimension.get("component") or ["?"])[0]
    if kind == "ArraySweep":
        return [f"sweep_{index} = ArraySweep({parameter}, np.asarray({dimension.get('array', '')}, dtype=float), "
                f"{delay!r}{extra})"]
    start, stop = _float(dimension.get("start"), 0.0), _float(dimension.get("stop"), 1.0)
    num = int(dimension.get("num", 101))
    if kind == "LogSweep":  # QCoDeS' LogSweep takes base-10 exponents; the fields hold the actual values
        return [f"sweep_{index} = LogSweep({parameter}, np.log10({start!r}), np.log10({stop!r}), {num}, {delay!r}{extra})"]
    return [f"sweep_{index} = LinSweep({parameter}, {start!r}, {stop!r}, {num}, {delay!r}{extra})"]


def _recipe_function(number, state, definitions, context):
    """The function that runs one recipe (or one step of the queue)."""
    if queue_steps.is_step(state):
        body = [f"    {line}" for line in queue_steps.python_lines(state)]
        return [f"def recipe_{number}():", f"    {_literal('Step: ' + recipe_tools.title(state))}", *body, '    return "done"']
    advanced = normalise_advanced(state.get("advanced"))
    dimensions = state.get("dimensions") or []
    title = recipe_tools.title(state)
    setup = {"experiment_parameters": definitions, "sweep": state}
    names = [d["name"] for d in required_definitions(setup)]
    measured_entries = [m for m in state.get("measured") or [] if m.get("path")]
    repeat = recipe_tools.repetitions(state)
    snake = len(dimensions) == 2 and bool(state.get("snake"))
    back_forth = recipe_tools.back_and_forth(state)
    swept = []
    for dimension in dimensions:
        for path in [dimension.get("component"), *(dimension.get("together") or [])]:
            if path and path[0] not in swept:
                swept.append(path[0])
    f = [f"def recipe_{number}():", f"    {_literal('Measurement: ' + title)}"]
    w = lambda text="": f.append(("    " + text) if text else "")
    namespace_items = ", ".join(f'"{n}": {n}' for n in names)
    w('namespace = {"np": np, "numpy": np, "time": time, "const": const, "station": station'
      + (", " + namespace_items if namespace_items else "") + "}  # what the actions can use")
    w(f"exp = load_or_create_experiment(experiment_name={_literal(state.get('experiment_name', '').strip() or 'Sweep')}, "
      "sample_name=SAMPLE_NAME)")
    w()
    for index, dimension in enumerate(dimensions, start=1):
        for line in _axis_lines(dimension, names, index):
            w(line)
    if snake:
        w("sweep_2 = make_snake(sweep_2)  # the inner axis goes back and forth")
    w("sweeps = [" + ", ".join(f"sweep_{i}" for i in range(1, len(dimensions) + 1)) + "]")
    if back_forth:
        w("backwards = [reverse_sweep(sweep) for sweep in sweeps]  # every other repetition sweeps backwards")
    w("measured = dict([")
    for entry in measured_entries:
        w(f"    measured_parameter({_literal(entry.get('alias', ''))}, {entry['path'][0]}),")
    w("])")
    w("parameters = list(measured.values())")
    w("measurement_name = " + _literal(state.get("measurement_name", "").strip()))
    # dond options
    w()
    w("enter_actions = [" + ", ".join(f"make_action({_literal(a['name'])}, {_text(a['code'])}, namespace)"
                                    for a in advanced["enter"] if a["enabled"]) + "]")
    w("exit_actions = [" + ", ".join(f"make_action({_literal(a['name'])}, {_text(a['code'])}, namespace)"
                                   for a in advanced["exit"] if a["enabled"]) + "]")
    w("additional_setpoints = [" + ", ".join(advanced["setpoints"]) + "]")
    datasets = advanced["datasets"]
    if datasets:
        w("dataset_setpoints = {" + ", ".join(
            f'{_literal(d["name"].strip())}: [{", ".join(d["setpoints"])}]' for d in datasets) + "}")
        w("dataset_measured = {" + ", ".join(
            f'{_literal(d["name"].strip())}: {_literal(d["measured"])}' for d in datasets) + "}")
    if state.get("breakout"):
        items = []
        for d in definitions:
            b = d.get("breakout") or {}
            if b.get("enabled") and d["name"] in names:
                items.append(f'({d["name"]!r}, {d["name"]}, {b.get("operator", ">")!r}, {_float(b.get("threshold"))!r}, '
                             f'{bool(b.get("absolute", True))!r})')
        w("break_condition = Breakout([" + ", ".join(items) + f"], parameters, mode={context.get('breakout_mode', 'any')!r})")
    else:
        w("break_condition = None")
    w()
    uses_export = advanced["export"] is not None
    if uses_export:
        w(f"_export = export_settings({advanced['export']!r}, {advanced['export_type']!r}, {advanced['export_path']!r})"
          "  # QCoDeS' automatic export, for this measurement")
        w("_export.__enter__()")
    w("for repetition in range(" + str(repeat) + "):")
    w("    if repetition and break_condition is not None and break_condition.reason:")
    w("        break  # a breakout condition ends the remaining repetitions too")
    if snake:
        w("    reset_snake(sweeps)  # the snake axis starts forward in every repetition")
    suffix = '"" if ' + str(repeat) + ' == 1 else f" [{repetition + 1}/' + str(repeat) + ']"'
    w(f"    suffix = {suffix}")
    if back_forth:
        w("    this_way = backwards if repetition % 2 else sweeps")
    if datasets:
        w('    names = [f"{measurement_name} - {name}{suffix}" for name in dataset_setpoints]')
        w("    dependencies = {")
        w("        run: dataset_setpoints[name] + [measured[m] for m in dataset_measured[name]]")
        w("        for run, name in zip(names, dataset_setpoints)")
        w("    }")
    else:
        w('    names = [f"{measurement_name}{suffix}"]')
    options = [
        "exp=exp", ("measurement_name=names" if datasets else "measurement_name=names[0]"),
        "enter_actions=enter_actions", "exit_actions=exit_actions", "additional_setpoints=additional_setpoints",
        "break_condition=break_condition",
        f"use_threads={context.get('use_threads') if advanced['use_threads'] is None else advanced['use_threads']!r}",
        "show_progress=True", "do_plot=False",
    ]
    if datasets:
        options.append("dataset_dependencies=dependencies")
    if advanced["write_period"] is not None:
        options.append(f"write_period={advanced['write_period']!r}")
    if advanced["in_memory_cache"] is not None:
        options.append(f"in_memory_cache={advanced['in_memory_cache']!r}")
    if advanced["log_info"].strip():
        options.append(f"log_info={advanced['log_info'].strip()!r}")
    w("    " + ("result = " if advanced["save_plot"] else "") + "dond(*" + ("this_way" if back_forth else "sweeps") + ", *parameters,")
    for option in options:
        w(f"         {option},")
    w("    )")
    if advanced["save_plot"]:
        w("    datasets = list(result[0]) if len(names) > 1 else [result[0]]")
        w(f"    save_dataset_plots(datasets, {advanced['plot_format']!r})  # qcodes.dataset.plot_dataset, saved next to the export")
    if uses_export:
        w("_export.__exit__(None, None, None)")
    if state.get("ramp_to_zero") and swept:
        w()
        w("# \"Ramp to 0 when finished\": each swept parameter goes to 0 at its maximum ramp rate")
        for name in swept:
            w(f"{name}(0)")
    w()
    w('return "breakout" if break_condition is not None and break_condition.reason else "done"')
    return f


def generate_script(recipes, context, definitions, name="queue.py"):
    """The text of the script. ``recipes``: the Measurement tab states, in queue order; ``definitions``: the
    experiment parameter definitions (dicts); ``context``: station_file, components, database, sample_name,
    stop_on_failure, breakout_mode, use_threads."""
    setup_all = {"experiment_parameters": definitions}
    needed = {}
    for state in recipes:
        for d in required_definitions({**setup_all, "sweep": state}):
            needed[d["name"]] = d
        if queue_steps.is_step(state):  # the parameters a step uses
            step = state[queue_steps.STEP_KEY]
            used = set(queue_steps.parameter_names(state))
            if step.get("expression"):
                try:
                    used |= {n.id for n in ast.walk(ast.parse(step["expression"], mode="eval")) if isinstance(n, ast.Name)}
                except SyntaxError:
                    pass
            for d in definitions:
                if d["name"] in used:
                    needed[d["name"]] = d
    uses_wait = any(
        (queue_steps.is_step(s) and s[queue_steps.STEP_KEY]["kind"].startswith(("wait", "set")) and s[queue_steps.STEP_KEY]["kind"] != "set")
        or (not queue_steps.is_step(s) and re.search(r"\bwait(_until|_below|_above|_stable)?\(", json.dumps(s)))
        for s in recipes)
    context = {**context, "uses_wait": uses_wait}
    uses_auto = any(not queue_steps.is_step(s) and (normalise_advanced(s.get("advanced"))["export"] is not None
                                                    or normalise_advanced(s.get("advanced"))["save_plot"]) for s in recipes)
    ordered = [d for d in definitions if d["name"] in needed]  # creation order: dependencies first
    uses_snake = any(len(s.get("dimensions") or []) == 2 and s.get("snake") for s in recipes)
    uses_trace = any(d.get("kind") == "trace" for d in ordered)
    uses_reverse = any(recipe_tools.back_and_forth(s) for s in recipes)

    out = [HEADER.format(date=datetime.now().strftime("%Y-%m-%d %H:%M"), count=len(recipes), name=name)]
    if uses_auto:
        from mesoscopy.core import auto_actions
        out.append("")
        out.append("# ---- automatic export and plots: copied from mesoscopy (core/auto_actions.py), QCoDeS only\n"
                   + _module_body(auto_actions))
    if uses_wait:
        from mesoscopy.core import wait_tools
        out.append("")
        out.append("# ---- waiting helpers: copied from mesoscopy (core/wait_tools.py)\n" + _module_body(wait_tools)
                   + "\n\nWAIT_FUNCTIONS = WaitTools().functions()  # wait, wait_until, wait_below, wait_above, wait_stable\n"
                   + "globals().update(WAIT_FUNCTIONS)")
    if uses_snake or uses_trace or uses_reverse:
        out.append("")
        if uses_trace:
            from mesoscopy.core import trace_parameter
            out.append("# ---- traces: copied from mesoscopy (core/trace_parameter.py)\n" + _module_body(trace_parameter))
        if uses_reverse:
            from mesoscopy.experiment import reverse
            out.append("# ---- back and forth: copied from mesoscopy (experiment/reverse.py)\n" + _module_body(reverse))
        if uses_snake:
            from mesoscopy.experiment import snake
            out.append("# ---- snake sweeps: copied from mesoscopy (experiment/snake.py)\n" + _module_body(snake))
    out.append("")
    out.append("# ================= SETTINGS =================")
    out.append(f"STATION_FILE = {context['station_file']!r}")
    out.append(f"COMPONENTS = {list(context['components'])!r}  # what was loaded in the application")
    out.append(f"DATABASE = {context['database']!r}")
    out.append(f"SAMPLE_NAME = {context['sample_name']!r}")
    out.append(f"STOP_ON_FAILURE = {bool(context['stop_on_failure'])!r}  # stop the queue when a measurement fails or hits a breakout condition")
    out.append("")
    out.append("station = Station(config_file=STATION_FILE)")
    out.append("for component in COMPONENTS:")
    out.append("    station.load_instrument(component)")
    out.append("initialise_or_create_database_at(DATABASE)")
    out.append(HELPERS.replace("__INTER_DELAY__", repr(RAMP_INTER_DELAY)))
    out.append("")
    out.append("# ================= EXPERIMENT PARAMETERS =================")
    names = {d["name"] for d in ordered}
    for d in ordered:
        out.extend(_definition_code(d, names))
    out.append("")
    out.append("# ================= MEASUREMENTS =================")
    for number, state in enumerate(recipes, start=1):
        out.append("")
        out.append("")
        out.extend(_recipe_function(number, state, definitions, context))
    out.append("")
    out.append("")
    out.append("RECIPES = [")
    for number, state in enumerate(recipes, start=1):
        out.append(f"    ({recipe_tools.title(state)!r}, recipe_{number}),")
    out.append("]")
    out.append("")
    out.append("")
    out.append('if __name__ == "__main__":')
    out.append("    for title, recipe in RECIPES:")
    out.append('        print(f"=== {title}")')
    out.append("        try:")
    out.append("            outcome = recipe()")
    out.append("        except Exception:")
    out.append("            traceback.print_exc()")
    out.append('            outcome = "failed"')
    out.append('        if outcome != "done" and STOP_ON_FAILURE:')
    out.append('            print(f"The queue stops: {title} {outcome}.")')
    out.append("            break")
    return "\n".join(out) + "\n"


def _module_body(module):
    """The source of a module, without its docstring (copied into the script)."""
    source = inspect.getsource(module)
    return re.sub(r'^""".*?"""\n', "", source, count=1, flags=re.S)
